[versions]

androidGradlePlugin = "8.5.2"
kotlin = "1.9.24"
googleServices = "4.4.2"

[libraries]

[plugins]

android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
google-services = { id = "com.google.gms.google-services", version.ref = "googleServices" }